### PR TITLE
Implment router to render specific components

### LINKED ISSUE #4: FE: Add and implement router to render specific components

### PR DESCRIPTION
**Pull request by aominhlong**
## Description 
Add and implement router to render specific components based on the url

#### Where to start?
Start in the `App.js` file

### `npm start`
Runs the app in the development mode.\
Open [http://localhost:3000](http://localhost:3000) to view it in your browser.
The page will reload when you make changes.
- change the end of the url to '/homepage', '/about' to see the changes

#### Issues
Closes #4  

#### Type of Change:
- [] Bug fix (non-breaking change which fixes an issue)
- [] Refactor (code is working and without bugs, formatting has been streamlined)
- [x] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### How Has This Been Tested?
What steps have you taken to ensure the code is effective?
- [x] Have you used Dev Tools/ ran code in the console?
- [] Have you ran the Cypress testing suite?

#### Checklist:
- [x] My code follows the style guidelines of this project.
- [x] My commit messages are consistent, descriptive, concise and begin with a verb and capital letter.
- [x] I have performed a self-review of my own code.
- [x] I have added reviewers.

### CODE REVIEW

**Review by Jlavarine — APPROVED** [review]
This is great Nick! Now our application has a multi-page feel to it. Great work!

**Review by JoshMallery — CHANGES_REQUESTED** [review]
Let's wrap all Routes in a Switch, so that we can have a catch-all at the end of the switch for error handling.

**Comment by aominhlong** [comment]
> Let's wrap all Routes in a Switch, so that we can have a catch-all at the end of the switch for error handling.

I just updated the 'App' file to include a Switch and error handling for bad URL

**Review by JoshMallery — APPROVED** [review]
Thanks for getting those changes in, The switch helps with error handling.

**Pull request merged**
